Repository Team-ComIT/koala, pull requests merged in 2022-08, with the labels that each got.

#13 merge: (#12) Domain Model 설계
  koala-domain/src/main/kotlin/comit/simsimpulyi/koala/domain/auth/error/.gitkeep
  koala-domain/src/main/kotlin/comit/simsimpulyi/koala/domain/auth/exception/.gitkeep
  koala-domain/src/main/kotlin/comit/simsimpulyi/koala/domain/auth/model/.gitkeep
  koala-domain/src/main/kotlin/comit/simsimpulyi/koala/domain/auth/service/.gitkeep
  koala-domain/src/main/kotlin/comit/simsimpulyi/koala/domain/feed/model/.gitkeep
  koala-domain/src/main/kotlin/comit/simsimpulyi/koala/domain/feed/model/Feed.kt
  koala-domain/src/main/kotlin/comit/simsimpulyi/koala/domain/like/error/.gitkeep
  koala-domain/src/main/kotlin/comit/simsimpulyi/koala/domain/like/exception/.gitkeep
  koala-domain/src/main/kotlin/comit/simsimpulyi/koala/domain/like/model/Like.kt
  koala-domain/src/main/kotlin/comit/simsimpulyi/koala/domain/like/service/.gitkeep
  koala-domain/src/main/kotlin/comit/simsimpulyi/koala/domain/user/model/User.kt
  koala-domain/src/main/kotlin/comit/simsimpulyi/koala/global/annotation/Aggregate.kt
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/persistence/feed/entity/FeedEntity.kt
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/persistence/user/entity/UserEntity.kt
Labels: feat

#17 merge: (#16) Aws S3 설계하기
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/DependencyVersions.kt
  buildSrc/src/main/kotlin/PluginVersions.kt
  koala-application/src/main/kotlin/comit/simsimpulyi/koala/domain/feed/spi/QueryFeedPort.kt
  koala-application/src/main/kotlin/comit/simsimpulyi/koala/domain/feed/spi/UploadFilePort.kt
  koala-application/src/main/kotlin/comit/simsimpulyi/koala/domain/like/spi/QueryLikePort.kt
  koala-application/src/main/kotlin/comit/simsimpulyi/koala/domain/user/spi/QueryUserPort.kt
  koala-domain/src/main/kotlin/comit/simsimpulyi/koala/domain/feed/model/Feed.kt
  koala-infrastructure/build.gradle.kts
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/config/.gitkeep
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/config/ConfigurationPropertiesConfig.kt
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/persistence/feed/FeedPersistenceAdapter.kt
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/persistence/feed/FeedRepository.kt
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/persistence/feed/mapper/FeedMapper.kt
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/persistence/file/FilePersistenceAdapter.kt
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/persistence/file/FileRepository.kt
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/persistence/file/entity/FileEntity.kt
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/persistence/like/LikePersistenceAdapter.kt
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/persistence/user/UserPersistenceAdapter.kt
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/persistence/user/UserRepository.kt
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/persistence/user/mapper/UserMapper.kt
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/thirdparty/aws/s3/.gitkeep
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/thirdparty/aws/s3/AwsS3Adapter.kt
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/thirdparty/aws/s3/AwsS3Properties.kt
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/thirdparty/aws/ses/.gitkeep
  koala-presentation/src/main/resources/application.yml
Labels: feat

#20 merge: (#18) Security 설계하기
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/DependencyVersions.kt
  koala-application/src/main/kotlin/comit/simsimpulyi/koala/domain/user/spi/ReceiveTokenPort.kt
  koala-infrastructure/build.gradle.kts
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/filter/.gitkeep
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/filter/FilterConfig.kt
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/filter/JwtFilter.kt
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/security/.gitkeep
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/security/SecurityConfig.kt
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/security/SecurityProperties.kt
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/security/principle/.gitkeep
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/security/principle/AuthDetails.kt
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/security/principle/AuthDetailsService.kt
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/security/token/.gitkeep
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/security/token/GenerateJwtAdapter.kt
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/security/token/JwtComponent.kt
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/security/token/JwtParser.kt
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/persistence/user/UserPersistenceAdapter.kt
  koala-presentation/src/main/resources/application.yml
Labels: feat

#22 merge: (#19) Exception 설정
  koala-domain/src/main/kotlin/comit/simsimpulyi/koala/global/error/.gitkeep
  koala-domain/src/main/kotlin/comit/simsimpulyi/koala/global/error/BusinessException.kt
  koala-domain/src/main/kotlin/comit/simsimpulyi/koala/global/error/ErrorProperty.kt
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/error/.gitkeep
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/error/ErrorResponse.kt
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/error/GlobalErrorCode.kt
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/error/GlobalErrorHandler.kt
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/exception/.gitkeep
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/exception/InternalServerErrorException.kt
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/filter/ExceptionFilter.kt
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/filter/FilterConfig.kt
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/security/SecurityConfig.kt
  koala-presentation/src/main/resources/application.yml
Labels: setting

#24 merge: (#21) 코드 스타일 리팩터링
  koala-application/src/main/kotlin/comit/simsimpulyi/koala/domain/feed/spi/UploadFilePort.kt
  koala-application/src/main/kotlin/comit/simsimpulyi/koala/domain/like/spi/QueryLikePort.kt
  koala-application/src/main/kotlin/comit/simsimpulyi/koala/domain/user/spi/ReceiveTokenPort.kt
  koala-domain/src/main/kotlin/comit/simsimpulyi/koala/domain/feed/model/File.kt
  koala-domain/src/main/kotlin/comit/simsimpulyi/koala/global/error/ErrorProperty.kt
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/.gitkeep
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/error/GlobalErrorHandler.kt
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/filter/ExceptionFilter.kt
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/filter/FilterConfig.kt
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/filter/JwtFilter.kt
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/security/principle/AuthDetailsService.kt
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/security/token/JwtParser.kt
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/persistence/BaseMapper.kt
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/persistence/BaseUUIDEntity.kt
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/persistence/feed/FeedPersistenceAdapter.kt
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/persistence/feed/FeedRepository.kt
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/persistence/feed/entity/FeedEntity.kt
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/persistence/feed/mapper/FeedMapper.kt
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/persistence/file/FilePersistenceAdapter.kt
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/persistence/file/FileRepository.kt
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/persistence/file/entity/FileEntity.kt
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/persistence/like/LikePersistenceAdapter.kt
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/persistence/like/entity/LikeEntity.kt
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/persistence/like/entity/LikeEntityId.kt
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/persistence/user/UserPersistenceAdapter.kt
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/persistence/user/UserRepository.kt
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/persistence/user/entity/UserEntity.kt
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/persistence/user/mapper/UserMapper.kt
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/thirdparty/aws/s3/UploadFileAdapter.kt
  koala-presentation/src/main/resources/application.yml
Labels: refactor

#25 merge: (#23) Signup 구현
  koala-application/src/main/kotlin/comit/simsimpulyi/koala/domain/feed/usecase/.gitkeep
  koala-application/src/main/kotlin/comit/simsimpulyi/koala/domain/feed/usecase/dto/.gitkeep
  koala-application/src/main/kotlin/comit/simsimpulyi/koala/domain/like/usecase/.gitkeep
  koala-application/src/main/kotlin/comit/simsimpulyi/koala/domain/like/usecase/dto/.gitkeep
  koala-application/src/main/kotlin/comit/simsimpulyi/koala/domain/user/spi/QueryUserPort.kt
  koala-application/src/main/kotlin/comit/simsimpulyi/koala/domain/user/usecase/SignupUseCase.kt
  koala-application/src/main/kotlin/comit/simsimpulyi/koala/domain/user/usecase/dto/DomainSignupRequest.kt
  koala-domain/src/main/kotlin/comit/simsimpulyi/koala/domain/user/model/User.kt
  koala-domain/src/main/kotlin/comit/simsimpulyi/koala/domain/user/spi/SecurityPort.kt
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/security/SecurityAdapter.kt
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/persistence/user/UserPersistenceAdapter.kt
  koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/persistence/user/UserRepository.kt
Labels: feat
